# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate

coverage:
  status:
    project:
      default:
        threshold: 0.1%

ignore:
  - "vendor/**/*"  # ignore all vendor sources
